name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build ⛏
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [ 14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        
    steps:
    - uses: actions/checkout@v2       
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build 
    - name: Archive production artifact
      uses: actions/upload-artifact@main
      with:
        name: build
        path: build
  
  deploy:
    name: Deploy 🚀
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Download artifact
        uses: actions/download-artifact@main
        with: 
          name: build
          path: build
      - name: Sync files to hosting
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "app-server-store"
          heroku_email: "ivan.perez.chan@hotmail.com"
